name: anakallumkal_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  animated_custom_dropdown: ^3.1.1
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.1.2
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2
  toastification: ^2.2.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/images/
    - assets/svgs/
    
